"""Core application components."""

from app.core.error_handling import (
    AADSException,
    DatabaseError,
    VisionProcessingError,
    NavtexProcessingError,
    AudioProcessingError,
    SensorReadingError,
    ModuleInitializationError,
    ExternalServiceError,
    ConfigurationError,
    AuthenticationError,
    ValidationError,
    ResourceNotFoundError,
    retry,
    ErrorContext,
    safe_execute,
    validate_coordinates,
    validate_confidence_score,
    AADSLogger,
)

__all__ = [
    "AADSException",
    "DatabaseError",
    "VisionProcessingError",
    "NavtexProcessingError",
    "AudioProcessingError",
    "SensorReadingError",
    "ModuleInitializationError",
    "ExternalServiceError",
    "ConfigurationError",
    "AuthenticationError",
    "ValidationError",
    "ResourceNotFoundError",
    "retry",
    "ErrorContext",
    "safe_execute",
    "validate_coordinates",
    "validate_confidence_score",
    "AADSLogger",
]
